apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::764694154057:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-4XhQCOuAgx9k
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::764694154057:user/vardhan
      username: vardhan
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-17T15:39:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1122"
  uid: c24f0769-8707-43d6-8e24-30abfbaaf3e9