apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::764694154057:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-oVOA8Ff3cUV8
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - groups:
        - roboshop-trainee
      userarn: arn:aws:iam::764694154057:user/vardhan
      username: vardhan
    - groups:
        - roboshop-admin
      userarn: arn:aws:iam::764694154057:user/vardhanbabu
      username: vardhanbabu