apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::764694154057:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-oVOA8Ff3cUV8
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
        - roboshop-trainee
      userarn: arn:aws:iam::764694154057:user/vardhan
      username: vardhan  
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-19T05:55:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1261"
  uid: 5d5f0704-fc2e-45b6-b224-47921189c5b8










  