apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::764694154057:role/eksctl-roboshop-addon-iamserviceaccount-robos-Role1-cLEUhvd6bCSe
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: roboshop-secret-reader
  namespace: roboshop
  




# this is for creating SA before this we need to install OIDC
  # eksctl create iamserviceaccount \
  # --name roboshop-secret-reader \
  # --namespace roboshop \
  # --cluster roboshop \
  # --attach-policy-arn arn:aws:iam::764694154057:policy/RoboshopSecretReader \
  # --approve
